package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Curso;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


public class CursoRepositoryDB implements CursoRepository {

    private final Connection connection;

    public CursoRepositoryDB(Connection connection) {
        this.connection = connection;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(String.valueOf(connection));
    }

    @Override
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS curso (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nombre VARCHAR(100) NOT NULL,
                  activo boolean NOT NULL
                );
                """;

        try {
            Statement st = connection.createStatement();
            st.execute(ddl);
        } catch (SQLException e) {
            throw new RuntimeException("Error inicializando schema", e);
        }
    }

    @Override
    public Optional<Curso> findById(Integer id) {
        String sql = "SELECT * FROM curso WHERE id = ?";
        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1, id);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return Optional.empty();
    }

    @Override
    public List<Curso> findAll() {
        String sql = "SELECT id, activo, nombre FROM curso";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            List<Curso> cursos = new ArrayList<>();
            while (rs.next()) {
                cursos.add(new Curso(rs.getInt("id"), rs.getBoolean("activo"), rs.getString("nombre")));
            }
            return cursos;

        }catch (SQLException e) {
            throw new RuntimeException("Error inicializando schema", e);
        }
    }

    @Override
    public Curso insert(Curso curso) {
        return null;
    }

    @Override
    public Curso update(Curso curso) {
        return null;
    }

    @Override
    public void eliminarCurso(String nombre) {
        String sql = "DELETE FROM curso WHERE nombre like ?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(1, "%" + nombre + "%");
            ps.executeUpdate();

        }catch(SQLException e){
            throw new RuntimeException("Error eliminando curso" + nombre, e);
        }
    }

}
